server.port: 8080

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/tweets?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace
